resolver: lts-12.24 # GHC 8.6.3
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/HaRe
- ./submodules/brittany
- ./submodules/cabal-helper
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core

- butcher-1.3.2.1
- cabal-plan-0.4.0.0
- constrained-dynamic-0.1.0.0
- haddock-api-2.21.0
- haskell-src-exts-1.21.0
- hlint-2.1.14
- hsimport-0.8.8
- hoogle-5.0.17.5
- monad-memo-0.4.1
- multistate-0.8.0.1
- optparse-simple-0.1.0
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
