jobs:
- job: Windows_installhs_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      shake:
        YAML_FILE: install/shake.yaml
  steps:
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
    displayName: Install stack
  - bash: |
      source .azure/windows.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows.bashrc
      stack --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie-install`
  - bash: |
      source .azure/windows.bashrc
      stack install.hs help
    displayName: Run help of `install.hs`
  - bash: |
      source .azure/windows.bashrc
      stack install.hs stack-install-cabal
    displayName: Run stack-install-cabal target of `install.hs`
  - bash: |
      source .azure/windows.bashrc
      stack install.hs build-latest
    displayName: Run build-latest target of `install.hs`
