jobs:
- job: Windows_installhs_Cabal
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  variables:
    YAML_FILE: install/shake.yaml
    PROJECT_FILE: install/shake.project
  steps:
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
    displayName: Install stack
  - bash: |
      source .azure/windows.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows.bashrc
      stack install cabal-install --stack-yaml $(YAML_FILE)
    displayName: Install `cabal-install`
  - bash: |
      source .azure/windows.bashrc
      cabal update
    displayName: update cabal
  # - bash: |
  #     source .azure/windows.bashrc
  #     stack --stack-yaml $(YAML_FILE) build --only-dependencies
  #   displayName: Build dependencies
  - bash: |
      source .azure/windows.bashrc
      cabal v2-build hie-install -w $(stack path --stack-yaml $(YAML_FILE) --compiler-exe) --project-file $(PROJECT_FILE)
    displayName: Build `hie-install`
  - bash: |
      source .azure/windows.bashrc
      cabal v2-run install.hs -w $(stack path --stack-yaml $(YAML_FILE) --compiler-exe) --project-file $(PROJECT_FILE) help
    displayName: Run help of `install.hs`
